onlyflans/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("web.urls")),
]

web/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import index, acerca, bienvenido, contacto, exito, registro, buscaflanes

app_name = "web"

urlpatterns = [
    path("", index, name="índice"),
    path("acerca", acerca, name="acerca"),
    path("bienvenido", bienvenido, name="bienvenido"),
    path("contacto", contacto, name="contáctanos"),
    path("exito", exito, name="éxito"),
    path("registrar", registro, name="regístrate"),
    path("accounts/login", auth_views.LoginView.as_view(template_name="registration/login.html"), name="login",),
    path("accounts/logout", auth_views.LogoutView.as_view(template_name="registration/logged_out.html"), name="logout",),
    path("buscaflan", buscaflanes, name="búscalo"),
]

web/models.py
import uuid

from django.db import models


class Flan(models.Model):
    flan_uuid = models.UUIDField(primary_key = True, default = uuid.uuid4, editable = False)
    name = models.CharField(max_length = 64)
    description = models.TextField()
    image_url = models.URLField()
    slug = models.SlugField(max_length = 50, allow_unicode = True)
    is_private = models.BooleanField()


class ContactForm(models.Model):
    contact_form_uuid = models.UUIDField(primary_key = True, default = uuid.uuid4, editable = False)
    customer_email = models.EmailField(max_length = 150)
    customer_name = models.CharField(max_length = 64)
    message = models.TextField()

web/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import ContactForm


class ContactFormForm(forms.Form):
    customer_email = forms.EmailField(label = 'Correo')
    customer_name = forms.CharField(max_length = 64, label = 'Nombre')
    message = forms.CharField(widget = forms.TextInput(attrs={'class': 'mensaje'}), label = 'Mensaje')


class ContactFormModelForm(forms.ModelForm):
    message = forms.CharField(widget = forms.Textarea(attrs={'rows': '4', 'cols': '30', 'style': 'resize: none;'}))
    
    class Meta:
        model = ContactForm
        fields = ['customer_name', 'customer_email', 'message']


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(label = "Correo electrónico")
    username = forms.CharField(label = "Nombre de usuario")
    password1 = forms.CharField(label = "Contraseña", widget = forms.PasswordInput)
    password2 = forms.CharField(label = "Confirmar contraseña", widget = forms.PasswordInput)

    class Meta:
            model = User
            fields = ['username', 'email', 'password1', 'password2']
            help_text = {k:"" for k in fields }

web/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib import messages

from .models import ContactForm, Flan
from .forms import ContactFormForm, ContactFormModelForm, UserRegisterForm


def index(request):
    public_flans = Flan.objects.filter(is_private=False)
    return render(request, "index.html", {"public_flans": public_flans})


def acerca(request):
    return render(request, "about.html", {})


@login_required
def bienvenido(request):
    private_flans = Flan.objects.filter(is_private=True)
    return render(request, "welcome.html", {"private_flans": private_flans})


def contacto(request):
    if request.method == "POST":
        form = ContactFormModelForm(request.POST)
        if form.is_valid():
            contact = ContactForm.objects.create(**form.cleaned_data)
            return HttpResponseRedirect("exito")
    else:
        form = ContactFormModelForm()
    return render(request, "contact.html", {"form": form})


def exito(request):
    return render(request, "success.html", {})


def registro(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            # El método '.save()' permite guardar en la BD el registro de la variable 'form'
            form.save()
            # Se inicia la sesión  del usuario inmediatemente después del registro.
            usuario = form.cleaned_data["username"]
            contrasena = form.cleaned_data["password1"]
            new_user = authenticate(username=usuario, password=contrasena)
            login(request, user=new_user)
            # Se agrega un mensaje de éxito.
            messages.success(request, f"Usuario {usuario} registrado exitosamente.")
            # Redirección a la página de inicio
            return HttpResponseRedirect("web")
    else:
        form = UserRegisterForm()
    return render(request, "register.html", {"form": form})


def buscaflanes(request):
    if request.method == "POST":
        # 'buscador' guarda el valor ingresado en el formulario de búsqueda.
        buscador = request.POST["buscador"]
        # Filtrar los distintos objetos flanes para que coincidan con nuestro
        # criterio de búsqueda. En este caso, con el nombre de cada flan.
        flanes = Flan.objects.filter(name__contains=buscador)
        return render(
            request,
            "results_flans.html",
            {
                "buscador": buscador,
                "flanes": flanes,
            },
        )
    else:
        return render(request, "results_flans.html", {})

web/templates/about.html
{% extends 'base.html' %} {% block 'contenido' %}
<div class="container p-5">
  <p class="my-4 fs-3">Acerca de OnlyFlans...</p>
  <p class="my-4 text-justify fs-5" id="lorem">
    OnlyFlans es una empresa dedicada a endulzar la vida de nuestros clientes
    con una gran variedad de postres y delicias de pastelería, con especialidad
    en flanes artesanales que destacan por su calidad y sabor inigualable.
    Fundada en 2021 en el corazón de Santiago de Chile, OnlyFlans surge como un
    emprendimiento familiar, inspirado en la tradición y en el cariño por los
    postres que reúne a las familias en momentos de alegría y celebración.
    Ubicados en Providencia, a pasos del metro Parque Bustamante, trabajamos
    cada día con el compromiso de ofrecer productos frescos y cuidadosamente
    elaborados, utilizando ingredientes de la más alta calidad. Nos enorgullece
    ser un lugar donde nuestros clientes pueden encontrar sabores auténticos y
    disfrutar de un momento dulce en su día.
  </p>
  <p class="my-4 text-justify fs-5" id="lorem">
    En OnlyFlans, creemos en la importancia de crear experiencias memorables a
    través de nuestros postres. Ya sea para una celebración especial o
    simplemente para un antojo, estamos aquí para hacer cada ocasión más dulce y
    especial.
  </p>
</div>
{% endblock 'contenido' %}

web/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <!-- Font Awesome Free -->
    <script
      src="https://kit.fontawesome.com/a263c2c0d7.js"
      crossorigin="anonymous"
    ></script>
    <!-- CSS -->
    <link rel="stylesheet" href="/static/css/styles.css" />
    <!--Titulo-->
    <title>Bienvenido a OnlyFlans</title>
    <!--<meta>-->
    <meta name="name" content="#" />
    <meta name="description" content="#" />
    <meta name="keywords" content="#" />
  </head>

  <body>
    {% block 'header' %} 
    {% include 'header.html' %} 
    {% endblock %} 

    {% block 'navbar' %} 
    {% include 'navbar.html' %}
    {% endblock %}

    {% block 'contenido' %}
    <div class="container">
      <p id="cont-text">contenido</p>
    </div>
    {% endblock %}
    
    {% block 'footer' %}
    {% include 'footer.html' %}
    {% endblock%}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
      integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

web/templates/contact.html
{% extends 'base.html' %}

{% block 'contenido' %}
<div class="container p-5" style="background-color: #ffc107;">
    <p class="my-4 fs-3">Contacto.</p>

    <form action="contacto" method="post" class="text-center">
    {% csrf_token %}

        {{ form.non_field_errors }}
        <div class="mb-3 text-center">
            <label for="{{ form.customer_name.id_for_label }}" class="form-label success fs-5 mb-0">
                Nombre:
            </label>
            <div>
                {{ form.customer_name }}
            </div>
            <div id="error-form">
                {{ form.customer_name.errors }}
            </div>
        </div>
        <div class="mb-3 text-center">
            <label for="{{ form.customer_email.id_for_label }}" class="form-label success fs-5 mb-0">
                Correo electrónico:
            </label>
            <div>
                {{ form.customer_email }}
            </div>
            <div id="error-form">
                {{ form.customer_email.errors }}
            </div>
        </div>
        <div class="mb-3 text-center">
            <label for="{{ form.message.id_for_label }}" class="form-label success fs-5 mb-0">
                Ingresa tu consulta:
            </label>
            <div>
                {{ form.message }}
            </div>
            <div id="error-form">
                {{ form.message.errors }}
            </div>
        </div>
        <input type="submit" value="Enviar" class="btn boton-sesion my-3">
    </form>
</div>
{% endblock 'contenido' %}

web/templates/footer.html
<footer class="container py-2" style="background-color: #fd7e14;">
    <div class="text-center py-2">
        <p class="fs-4 my-auto">Creado por Esteban Hernández</p>
    </div>
    <div class="row mx-2 mx-md-4 mx-xl-5 pb-2">
        <div class="d-inline-block col-6 mx-auto text-center display-6">
            <a href="https://www.linkedin.com/in/esteban-hern%C3%A1ndez-c%C3%A1ceres-979a46208/" target="_blank"
                class="footer-ico mx-2" data-bs-toggle="tooltip" data-bs-placement="left"
                title="Esteban Hernández Cáceres Linkedin"><i class="fa-brands fa-linkedin footer-ico"></i>
            </a>
            <a href="https://github.com/stivhc" target="_blank" class="footer-ico mx-2" data-bs-toggle="tooltip" data-bs-placement="right" title="Esteban Hernández Cáceres GitHub"><i class="fa-brands fa-github-square footer-ico"></i>
            </a>
        </div>
    </div>
</footer>

web/templates/header.html
{% load static %}
<header class="container" style="background-color: #0dcaf0;">
  <div class="text-center">
    <img
      class="img-fluid my-3"
      src="{% static 'imglogo_onlyflans-white.png'}"
      alt="OnlyFlans"
    />
  </div>
</header>

web/templates/index.html
{% extends 'base.html' %} {% block 'contenido' %}

<div class="container p-5">
  {% if messages %} {% for message in messages %}
  <div class="mb-4 fs-3 alert alert-dark {{message.tags}}">{{ message }}</div>
  {% endfor %} {% endif %}
  <div class="shadow p-3 informacion rounded" style="background-color: #ffc107;">
    <p class="mb-1 fs-3">Nuestros flanes</p>
    <p class="fs-6">
      Buscamos los secretos mejor guardados de nuestras abuelas para entregarte
      los mejores flanes.
    </p>
    <a
      role="button"
      class="btn boton-sesion px-0 fs-5"
      href="{% url 'web:acerca' %}"
      >Conócenos</a
    >
  </div>
  <div class="row">
    {% for flan in flanes %}

    <div class="col-12 col-md-6 col-lg-4 col-xl-3 mt-5 mb-2">
      <div class="card shadow">
        <img src="{{ flan.image_url }}" class="img-fluid" alt="Al rico flan" />
        <div class="card-body">
          <h5 class="card-title" id="hola">{{ flan.name }}</h5>
          <p class="card-text">{{ flan.description }}</p>
        </div>
      </div>
    </div>

    {% endfor %}
  </div>
</div>

{% endblock 'contenido' %}

web/templates/navbar.html
<nav class="container" style="background-color: #dd5563;">
    <div class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'web:índice' %}">Inicio</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'web:bienvenido' %}">Bienvenido</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'web:acerca' %}">Acerca</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'web:contáctanos' %}">Contacto</a>
                    </li>
                </ul>
            </div>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
            {% if not user.is_authenticated %}
                <a role="button" class="btn boton-sesion ms-auto" href="{% url 'web:login' %}">Inicia sesión</a>
                <a role="button" class="btn boton-sesion ms-3" href="{% url 'web:regístrate' %}">Regístrate</a>
            {% else %}
                <a role="button" class="btn boton-sesion ms-auto" href="{% url 'web:logout' %}">Cierra sesión</a>
            {% endif %}
            </div>
        </div>
    </div>
</nav>

web/templates/register.html
{% extends 'base.html' %} {% block 'contenido' %}
<div class="container p-5">
  <p class="my-4 fs-3">Registro de usuarios.</p>
  <div class="row text-center">
    <div class="card col-12 col-md-6 col-lg-4 col-xl-3 mx-auto sin-borde">
      <div class="card-body">
        {% if not user.is_authenticated %}
        <form method="post" class="">
          {% csrf_token %} {{ form.as_p }}
          <input
            type="submit"
            value="Regístrate"
            class="btn boton-sesion my-3"
          />
        </form>
        {% else %}
        <div class="my-4 fs-3 alert alert-dark">
          Ya eres un usuario registrado, {{ user.username }}.
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock 'contenido' %}

web/templates/results_flans.html
{% extends 'base.html' %} {% block 'contenido' %}
<div class="container p-5">
  {% if not user.is_authenticated %}
  <h3>No tienes acceso a esta sección.</h3>
  <br />
  <a class="fs-6 logout" href="{% url 'web:login' %}">Si quieres ver más productos inicia tu sesión.</a>
  {% else %} {% if buscador %}
  <p class="mt-4 mb-2 fs-3">Estos flanes coinciden con {{ buscador }}:</p>

  <div class="row" style="background-color: #ffc107;">
    {% for flan in flanes %}
    <div class="col-12 col-md-6 col-lg-4 col-xl-3 mt-5 mb-2">
      <div class="card shadow">
        <img src="{{ flan.image_url }}" class="img-fluid" alt="Al rico flan" />
        <div class="card-body">
          <h5 class="card-title" id="hola">{{ flan.name }}</h5>
          <p class="card-text">{{ flan.description }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <p class="my-4 fs-3">No has realizado tu búsqueda aún.</p>
  {% endif %}
  {% block 'searcher' %}
  {% include 'search_flans.html' %}
  {%endblock %}
  {% endif %}
</div>
{% endblock 'contenido' %}

web/templates/search_flans.html
<div class="mt-5 text">
    <p class="my-4 fs-3">Encuentra tu flan:</p>
    <form action="{% url 'web:búscalo' %}" method="post" clas="">
        {% csrf_token %}
        <div class="row ps-0 mx-0">
            <div class="ps-0 mb-3 mb-lg-0 col-12 col-lg-9 col-xl-10">
                <input class="me-4 form-control" type="search" placeholder="Encuentra tu flan..."
                    aria-label="Encuentra tu flan" name="buscador">
            </div>
            <button class="btn boton-sesion ms-auto col-12 col-lg-3 col-xl-2" type="submit" style="background-color:  #0d6efd;">Buscar</button>
        </div>
    </form>
</div>

web/templates/success.html
{% extends 'base.html' %} {% block 'contenido' %}
<div class="container p-5 succes text-center">
  <h3>¡Gracias por contactarte con OnlyFlans!</h3>
  <h3>Te responderemos a la brevedad.</h3>
  <a
    role="button"
    class="btn btn-primary boton-sesion mt-5"
    href="{% url 'web:índice' %}"
    >Volver al inicio</a
  >
</div>
{% endblock 'contenido' %}

<div class="container p-5 text-center">
  <h3>Has cerrado tu sesión correctamente.</h3>
  <a class="fs-5 logout mx-3" href="{% url 'web:índice' %}">Vuelve al Inicio</a>
  |
  <a class="fs-5 logout mx-3" href="{% url 'web:login' %}"
    >Reinicia tu sesión</a
  >
</div>

web/templates/welcome.html
{% extends 'base.html' %} {% block 'contenido' %}
<div class="container p-5">
  <div class="shadow p-3 informacion rounded" style="background-color: #ffc107;">
    <p class="mb-1 fs-3">Bienvenido {{ user.username }}</p>
    <p class="fs-6">
      Tenemos los más exclusivos productos para conquistar tu paladar ¿Quieres
      conocerlos?
    </p>
    <a
      role="button"
      class="btn boton-sesion px-0 fs-5"
      href="{% url 'web:contáctanos' %}"
      >Contáctanos</a
    >
  </div>

  {% block 'searcher' %} {% include 'search_flans.html' %} {% endblock %}

  <div class="row">
    {% for flan in flanes %}
    <div class="col-12 col-md-6 col-lg-4 col-xl-3 mt-5 mb-2">
      <div class="card shadow">
        <img src="{{ flan.image_url }}" class="img-fluid" alt="Al rico flan" />
        <div class="card-body">
          <h5 class="card-title" id="hola">{{ flan.name }}</h5>
          <p class="card-text">{{ flan.description }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock 'contenido' %}